function decodificadorLZW_Sebastian_Lombranna_Alberto(filenameInputCompressed,filenameOutputUncompressed)
%DECODIFICADORLZW_SEBASTIAN_LOMBRANNA_ALBERTO This decoder implements the Lempel-Ziv-Welch algorithm

end